### ISSUE TITLE
npm install error on macOS (Catalina 10.15.5)

### ISSUE THREAD

**Issue by RanveerMeel** [Kalaam-Programming-Language/Kalaam#12]
When is try to install Kalaam on mac it is given below error. Is this my system issue or project does not support it ?

`ranveermeel@Ranveers-MacBook-Pro Kalaam % npm install

> fsevents@1.2.11 install /Users/ranveermeel/repos/Kalaam/node_modules/fsevents
> node-gyp rebuild

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ranveermeel/repos/Kalaam/node_modules/fsevents
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

> core-js@2.6.11 postinstall /Users/ranveermeel/repos/Kalaam/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> core-js@3.6.1 postinstall /Users/ranveermeel/repos/Kalaam/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> ejs@2.7.4 postinstall /Users/ranveermeel/repos/Kalaam/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 1186 packages from 1727 contributors and audited 1257 packages in 114.88s

32 packages are looking for funding
  run `npm fund` for details

found 794 vulnerabilities (788 low, 5 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
ranveermeel@Ranveers-MacBook-Pro Kalaam %`

**Comment by RanveerMeel** [comment]
`ranveermeel@Ranveers-MacBook-Pro ~ % npm --version
6.14.4
ranveermeel@Ranveers-MacBook-Pro ~ % sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.5
BuildVersion:	19F101`

**Comment by RanveerMeel** [comment]
Solution 👍 
https://stackoverflow.com/questions/60573595/npm-install-fails-on-node-gyp-rebuild-with-gyp-no-xcode-or-clt-version-detec
